/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Clases.Database;
import java.sql.*;

/**
 *
 * @author lalzate
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public Database database;   
    
    public Login(){
        this.database = new Database();
        database.DatabaseConnection();
        initComponents();
    }
    
    
    /* Función para inicio de sesión */
    public void logIn(){
        String user = this.userField.getText();
        String password = String.valueOf(this.passwordField.getPassword());
        /* Se validan campos vacíos */
        if(!user.equals("") && !password.equals("")){
            try {
                boolean userValidation = this.database.userValidation(user, password);
                /* Se valida la respuesta de la función que valida al usuario */
                if(userValidation){
                    System.out.println("Usuario encontrado");
                }else{
                    System.out.println("Usuario no encontrado");
                }
                
            } catch (Exception e) {
                System.out.println("Error al iniciar sesión" + e.getMessage());
            }
        }else{
            System.out.println("Campos vacios");
        }
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRound1 = new LIB.JPanelRound();
        fSTexFieldMD1 = new LIB.FSTexFieldMD();
        fSPasswordFieldMD1 = new LIB.FSPasswordFieldMD();
        jPanelRound2 = new LIB.JPanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanelRound1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound1.setOpaque(true);
        jPanelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fSTexFieldMD1.setBackground(new java.awt.Color(255, 255, 255));
        fSTexFieldMD1.setForeground(new java.awt.Color(23, 146, 244));
        fSTexFieldMD1.setBordeColorFocus(new java.awt.Color(23, 146, 244));
        fSTexFieldMD1.setBordeColorNoFocus(new java.awt.Color(153, 153, 153));
        fSTexFieldMD1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fSTexFieldMD1.setMaterialDesing(true);
        fSTexFieldMD1.setPlaceholder("Username");
        jPanelRound1.add(fSTexFieldMD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 128, -1, -1));

        fSPasswordFieldMD1.setBackground(new java.awt.Color(255, 255, 255));
        fSPasswordFieldMD1.setForeground(new java.awt.Color(26, 146, 244));
        fSPasswordFieldMD1.setBordeColorFocus(new java.awt.Color(23, 146, 244));
        fSPasswordFieldMD1.setBordeColorNoFocus(new java.awt.Color(153, 153, 153));
        fSPasswordFieldMD1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fSPasswordFieldMD1.setMaterialDesing(true);
        fSPasswordFieldMD1.setPlaceholder("Password");
        jPanelRound1.add(fSPasswordFieldMD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jPanelRound2.setArch(30);
        jPanelRound2.setArcw(30);
        jPanelRound2.setColorSecundario(new java.awt.Color(23, 146, 244));

        javax.swing.GroupLayout jPanelRound2Layout = new javax.swing.GroupLayout(jPanelRound2);
        jPanelRound2.setLayout(jPanelRound2Layout);
        jPanelRound2Layout.setHorizontalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanelRound2Layout.setVerticalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanelRound1.add(jPanelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 323, 240, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSPasswordFieldMD fSPasswordFieldMD1;
    private LIB.FSTexFieldMD fSTexFieldMD1;
    private LIB.JPanelRound jPanelRound1;
    private LIB.JPanelRound jPanelRound2;
    // End of variables declaration//GEN-END:variables
}
