/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Clases.Database;
import java.awt.Color;
import Dashboard.Dashboard;

/**
 *
 * @author lalzate
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public Database database;   
    
    public Login(){
        this.database = new Database();
        database.DatabaseConnection();
        initComponents();
        Login.this.setBackground(new Color(0, 0, 0, 0));
    }
    
    
    /* Función para inicio de sesión */
    public void logIn(){
        String user = this.userField.getText();
        String password = String.valueOf(this.passwordField.getPassword());
        /* Se validan campos vacíos */
        if(!user.equals("") && !password.equals("")){
            try {
                boolean userValidation = this.database.userValidation(user, password);
                /* Se valida la respuesta de la función que valida al usuario */
                if(userValidation){
                    System.out.println("Usuario encontrado");
                    dispose();
                    Dashboard dashboard = new Dashboard();
                    dashboard.setVisible(true);
                }else{
                    System.out.println("Usuario no encontrado");
                }
                
            } catch (Exception e) {
                System.out.println("Error al iniciar sesión" + e.getMessage());
            }
        }else{
            System.out.println("Campos vacios");
        }
    }
    
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRound1 = new LIB.JPanelRound();
        userField = new LIB.FSTexFieldMD();
        passwordField = new LIB.FSPasswordFieldMD();
        jPanelRound2 = new LIB.JPanelRound();
        jLabel2 = new javax.swing.JLabel();
        fSGradientPanel1 = new LIB.FSGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        exitButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanelRound1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound1.setOpaque(true);
        jPanelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userField.setForeground(new java.awt.Color(23, 146, 244));
        userField.setBordeColorFocus(new java.awt.Color(23, 146, 244));
        userField.setBordeColorNoFocus(new java.awt.Color(153, 153, 153));
        userField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userField.setMaterialDesing(true);
        userField.setPlaceholder("Username");
        jPanelRound1.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        passwordField.setForeground(new java.awt.Color(26, 146, 244));
        passwordField.setBordeColorFocus(new java.awt.Color(23, 146, 244));
        passwordField.setBordeColorNoFocus(new java.awt.Color(153, 153, 153));
        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordField.setMaterialDesing(true);
        passwordField.setPlaceholder("Password");
        jPanelRound1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jPanelRound2.setBackground(new java.awt.Color(23, 146, 244));
        jPanelRound2.setArch(30);
        jPanelRound2.setArcw(30);
        jPanelRound2.setColorSecundario(new java.awt.Color(38, 48, 51));
        jPanelRound2.setOpaque(true);
        jPanelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Iniciar sesión");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanelRound2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 250, 50));

        fSGradientPanel1.setBackground(new java.awt.Color(23, 146, 244));
        fSGradientPanel1.setFSEndColor(new java.awt.Color(51, 75, 166));
        fSGradientPanel1.setFSGradientFocus(150);
        fSGradientPanel1.setFSStartColor(new java.awt.Color(23, 146, 244));

        javax.swing.GroupLayout fSGradientPanel1Layout = new javax.swing.GroupLayout(fSGradientPanel1);
        fSGradientPanel1.setLayout(fSGradientPanel1Layout);
        fSGradientPanel1Layout.setHorizontalGroup(
            fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        fSGradientPanel1Layout.setVerticalGroup(
            fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanelRound2.add(fSGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -16, -1, 70));

        jPanelRound1.add(jPanelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 260, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar sesión");
        jPanelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 330, -1));

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon-x.png"))); // NOI18N
        exitButton.setText("jLabel3");
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
        });
        jPanelRound1.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 40, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
            System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonMouseEntered

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        logIn();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitButton;
    private LIB.FSGradientPanel fSGradientPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private LIB.JPanelRound jPanelRound1;
    private LIB.JPanelRound jPanelRound2;
    private LIB.FSPasswordFieldMD passwordField;
    private LIB.FSTexFieldMD userField;
    // End of variables declaration//GEN-END:variables
}
